spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4201"
            allowedHeaders: "*"
            allowedMethods: "*"